# Generated by Django 5.2.7 on 2025-10-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='N/A', max_length=100)),
                ('edad', models.IntegerField(default=18)),
                ('puestoAsignado', models.CharField(default='Asistente', max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('horario', models.CharField(default='9:00 - 17:00', max_length=50)),
                ('telefono', models.CharField(default='000-000-0000', max_length=15)),
                ('tipoProducto', models.CharField(default='General', max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('id_ventas', models.IntegerField(default=1)),
            ],
        ),
    ]
